### ISSUE TITLE
Erro "cancelapa"

### ISSUE THREAD

**Issue by hukunoz** [gofas/whmcs-gerencianet-dashboard#1]
A transação #XXXX não pode ser cancelapa pois já foi cancelada.

**Comment by mauriciogofas** [comment]
Você não pode cancelar uma transação que já foi cancelada, apenas transações com status "aguardando" e "não pago" podem ser canceladas.

**Comment by hukunoz** [comment]
A abertura desse issue é para correção da palava "cancelapa".

**Comment by mauriciogofas** [comment]
Ah é, vc não explicou e eu não percebi.
Já vou corrigir é melhorar essa frase, gratidão por reportar.

**Comment by mauriciogofas** [comment]
[Corrigido](https://github.com/gofas/whmcs-gerencianet-dashboard/blob/master/gofasgerencianet/gofasgerencianet.php#L235), deixei apenas "A transação #XXXX já foi cancelada."
